# Generated by Django 5.1.4 on 2025-01-03 06:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('notify_events', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Demo Request',
                'verbose_name_plural': 'Demo Requests',
            },
        ),
    ]
