# Generated by Django 4.2.3 on 2025-01-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_clientfeedback"),
    ]

    def add_default_services(apps, schema_editor):
        Serivces = apps.get_model("core", "Serivces")
        Serivces.objects.create(
            title="AI-powered Virtual Assistant",
            description="Revolutionize your digital employee experience with our AI-powered virtual assistant, built to support and accelerate your workflow.",
        )
        Serivces.objects.create(
            title="AI-based Prototyping",
            description="Speed up design and engineering processes with affordable AI-based prototyping solutions tailored to your needs.",
        )
        Serivces.objects.create(
            title="Customer Solutions",
            description="Providing personalized AI-driven solutions to meet the unique needs of various industries for faster, smarter outcomes.",
        )
    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("venue", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date", models.DateField()),
                ("notify_users", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.CreateModel(
            name="Serivces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.RunPython(add_default_services, migrations.RunPython.noop),
    ]
